#!/usr/bin/env python3
"""Deterministic half of the mental-model list in data/mental-models.md.

  mental_models.py names                print every model name linked in wiki/ and topics/ as
                                        "uses<TAB>name<TAB>variant-key", most used first
  mental_models.py build [--map FILE]   rewrite data/mental-models.md with fresh use counts;
                                        with --map, take the entries from FILE (JSON object
                                        {canonical: [alias, ...]}) instead of the current list
  mental_models.py unlisted             print model names used in wiki/ or topics/ that are not a listed
                                        model, an alias, or an excluded label, as JSON with use
                                        counts and a likely match where only spelling differs
  mental_models.py add NAME             list NAME as a model
  mental_models.py alias NAME --to M    list NAME as an alias of model M
  mental_models.py exclude NAME         record NAME as a reviewed label that is not a model

Every command that changes the list rewrites data/mental-models.md with fresh use counts.
With build --map, names that the map doesn't cover are written to
data/mental-models-excluded.md, so they aren't offered for review again.

Model names are harvested from wiki/ and topics/, in two places: bullets in the old
"## 🧠 First Principles & Mental Models" section, and "*model:* [[Name]]" in the
"## 🧠 Core Principles" section written by /kb-ingest and /kb-compound.

Run from the vault root. Standard library only.
"""
import argparse
import json
import re
import sys
from collections import Counter
from pathlib import Path

LIST_PATH = Path("data/mental-models.md")
EXCLUDED_PATH = Path("data/mental-models-excluded.md")
OLD_SECTION = re.compile(r"^## 🧠 First Principles & Mental Models\n(.*?)(?=^## |\Z)", re.S | re.M)
NEW_SECTION = re.compile(r"^## 🧠 Core Principles\n(.*?)(?=^## |\Z)", re.S | re.M)
OLD_ENTRY = re.compile(r"^- \*\*\[\[([^\]|]+)", re.M)
NEW_ENTRY = re.compile(r"\*model:\*\s*\[\[([^\]|]+)")
ROW = re.compile(r"^\| \[\[([^\]]+)\]\] \| (.*?) \| *\d+ *\|$", re.M)
ALIAS_SEP = "; "

HEADER = """# Mental Models

Canonical names for the mental models linked in wiki notes. `/kb-ingest` uses this list when it names the model behind a Core Principle, so the same model always gets the same `[[link]]`.

- **Model** is the spelling to link. **Aliases** are other spellings and near-synonyms that mean the same model; write the Model name instead of any of them.
- A model that isn't listed may still be named by its standard name. `/kb-librarian` collects unlisted names for review, and `/kb-librarian-apply` adds the approved ones.
- One-off labels coined for a single article (e.g. "Decoupling Dividend") don't belong here.
- **Uses** counts links across `wiki/` and `topics/` (Model plus Aliases). It is regenerated by `.claude/skills/kb-librarian/scripts/mental_models.py build`, so don't edit it by hand.

| Model | Aliases | Uses |
|-------|---------|-----:|
"""


EXCLUDED_HEADER = """# Excluded model names

Names used as mental-model links in wiki notes that were reviewed and judged not to be established mental models, usually labels coined for one article. `/kb-librarian` skips these when it collects unlisted names. Listed models are in `mental-models.md`.

"""


def variant_key(name):
    """Collapse differences of case, punctuation, articles and plurals."""
    k = name.lower().replace("’", "'")
    k = re.sub(r"[^a-z0-9 ]", " ", k)
    k = re.sub(r"\b(the|a|an)\b", " ", k)
    return " ".join(w[:-1] if w.endswith("s") and len(w) > 3 else w for w in k.split())


def harvest(roots=(Path("wiki"), Path("topics"))):
    uses = Counter()
    for path in (p for root in roots for p in root.rglob("*.md")):
        text = path.read_text(errors="ignore")
        for section, entry in ((OLD_SECTION, OLD_ENTRY), (NEW_SECTION, NEW_ENTRY)):
            match = section.search(text)
            if match:
                uses.update(name.strip() for name in entry.findall(match.group(1)))
    return uses


def load_list(path=LIST_PATH):
    if not path.exists():
        return {}
    entries = {}
    for canonical, aliases in ROW.findall(path.read_text()):
        entries[canonical] = [a for a in aliases.split(ALIAS_SEP) if a.strip()]
    return entries


def load_excluded(path=EXCLUDED_PATH):
    if not path.exists():
        return []
    return [line[2:].strip() for line in path.read_text().splitlines() if line.startswith("- ")]


def write_excluded(names, path=EXCLUDED_PATH):
    body = "\n".join(f"- {n}" for n in sorted(set(names), key=str.lower))
    path.write_text(EXCLUDED_HEADER + body + "\n")


def lookup(entries):
    """Map every listed spelling (exact and variant key) to its canonical name."""
    table = {}
    for canonical, aliases in entries.items():
        for name in [canonical, *aliases]:
            table[name.lower()] = canonical
            table.setdefault(variant_key(name), canonical)
    return table


def render(entries, uses):
    rows = []
    for canonical in sorted(entries, key=str.lower):
        aliases = sorted(set(entries[canonical]) - {canonical}, key=str.lower)
        count = sum(uses.get(name, 0) for name in [canonical, *aliases])
        rows.append(f"| [[{canonical}]] | {ALIAS_SEP.join(aliases)} | {count} |")
    return HEADER + "\n".join(rows) + "\n"


def cmd_names(_):
    for name, count in harvest().most_common():
        print(f"{count}\t{name}\t{variant_key(name)}")


def save(entries):
    LIST_PATH.write_text(render(entries, harvest()))
    print(f"wrote {LIST_PATH} ({len(entries)} models)")


def covered(entries):
    return {name.lower() for c, a in entries.items() for name in [c, *a]}


def cmd_build(args):
    if args.map:
        entries = json.loads(Path(args.map).read_text())
        known = covered(entries)
        rest = [name for name in harvest() if name.lower() not in known]
        write_excluded(rest + [n for n in load_excluded() if n.lower() not in known])
        print(f"wrote {EXCLUDED_PATH} ({len(set(rest))} names not covered by the map)")
    else:
        entries = load_list()
    if not entries:
        sys.exit("no entries: pass --map or create data/mental-models.md first")
    save(entries)


def drop_excluded(name):
    remaining = [n for n in load_excluded() if n.lower() != name.lower()]
    if len(remaining) != len(load_excluded()):
        write_excluded(remaining)


def cmd_add(args):
    entries = load_list()
    if args.name.lower() in covered(entries):
        sys.exit(f"already listed: {args.name}")
    entries[args.name] = []
    drop_excluded(args.name)
    save(entries)


def cmd_alias(args):
    entries = load_list()
    if args.to not in entries:
        sys.exit(f"not a listed model: {args.to}")
    if args.name.lower() in covered(entries):
        sys.exit(f"already listed: {args.name}")
    entries[args.to].append(args.name)
    drop_excluded(args.name)
    save(entries)


def cmd_exclude(args):
    if args.name.lower() in covered(load_list()):
        sys.exit(f"listed as a model or alias, remove it from {LIST_PATH} first: {args.name}")
    write_excluded(load_excluded() + [args.name])
    print(f"excluded: {args.name}")


def cmd_unlisted(_):
    entries = load_list()
    exact = covered(entries) | {n.lower() for n in load_excluded()}
    by_key = lookup(entries)
    out = []
    for name, count in harvest().most_common():
        if name.lower() in exact:
            continue
        out.append({"name": name, "uses": count, "likely_alias_of": by_key.get(variant_key(name))})
    print(json.dumps(out, indent=2, ensure_ascii=False))


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="cmd", required=True)
    sub.add_parser("names").set_defaults(func=cmd_names)
    build = sub.add_parser("build")
    build.add_argument("--map")
    build.set_defaults(func=cmd_build)
    sub.add_parser("unlisted").set_defaults(func=cmd_unlisted)
    for cmd, func in (("add", cmd_add), ("exclude", cmd_exclude)):
        p = sub.add_parser(cmd)
        p.add_argument("name")
        p.set_defaults(func=func)
    alias = sub.add_parser("alias")
    alias.add_argument("name")
    alias.add_argument("--to", required=True)
    alias.set_defaults(func=cmd_alias)
    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
